name: SimpleNPCs
version: ${project.version}
main: com.github.arnhav.SimpleNPCs
api-version: 1.18
depend: [ ProtocolLib ]
authors: [ Tyrriel ]
commands:
  snpc:
    usage: /<command>
    description: SimpleNPC command
